<?php echo $this->createTemplateTop(); ?>

<body <?php if ($this->isMainPage()) { ?>class="index" <?php } ?>>
    <main>
        <div id="headline">
            <h1><span id="generateTitle">Generate</span> <span id="someTitle">some</span> <span id="typeTitle">colors</span> + <span id="generateTitle">Generate</span> <span id="someTitle">some</span> <span id="typeTitle">words</span></h1>
        </div>
    <div id="creation" class="border">
        <button type="button"
        onclick="ButtonPress()">
        Start</button>
        <p style="text-align:center" id="demo"></p>
        <p style="text-align:center" id="infoText"></p>
    </div>
    </main>
</body>

<script>
        function ButtonPress() {
            let input = prompt("How many runs?", "20");
            const [
                runs,
                timeout
            ] = input.split(",");

            if (runs == null || runs == "") {
                alert("You didn't gave me a number... :(")
            } else if(isNaN(runs)){
                alert(`${runs} isn't a number.. :(`)
            } else {
                createColors(Number(runs), timeout);
            }
        };


        function createColors(runs = 20, timeout = 250) {
            const ColorArray = new Array(
                    "Red",
                    "Green",
                    "Blue",
                    "Yellow",
                    "Purple",
                    "Orange",
                    "Black",
                    "Aquamarine",
                    "Aqua",
                    "Brown",
            );

            function getRandom(Array) {
                return { 
                    rColor: Array[Math.floor(Math.random()*Array.length)],
                    rStyle: Array[Math.floor(Math.random()*Array.length)],
                }
            } 
       
            const now = new Date()
            let number = 1;
            const waitTexts = new Array(
                "Creating...",
                "Please wait until I created all Colors!"
            )

            if(waitTexts.includes(document.getElementById('infoText').innerHTML)) { 
                document.getElementById('infoText').innerHTML = waitTexts[1];
                return alert(waitTexts[1]);
            } else if(document.getElementById('infoText').innerHTML.includes("Created")) {
                document.getElementById('demo').innerHTML = ` `;
                document.getElementById('infoText').innerHTML = waitTexts[0];
            } else document.getElementById('infoText').innerHTML = waitTexts[0];

            for(i = 0; i < runs; i++) {
                setTimeout(() => {
                    const { rColor, rStyle } = getRandom(ColorArray);
                    number++;

                    
                    if(number === 1) document.getElementById('demo').innerHTML = `<p style="color:${rStyle}">` + rColor + "</p>";
                    else document.getElementById('demo').innerHTML = document.getElementById('demo').innerHTML + `<p style="color:${rStyle}">` + rColor + "</p>";


                    if(number === (runs + 1)) {
                        document.getElementById('infoText').innerHTML = `<p>Created ${runs} Random Colors after ${~~(new Date() - now) / 1000} seconds</p>`;
                    }

                }, i * timeout) 
            }
        }
    </script>
</html>
