<?php echo $this->doctype() ?>
<html lang="<?php echo $this->getLanguage(); ?>">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <title>Color Creator</title>
</head>

<body <?php if ($this->isMainPage()) { ?>class="index" <?php } ?>>
    <main>
        <div id="headline">
            <h1><span>Generate</span> <span>some</span> <span>colors</span> + <span>Generate</span> <span>some</span> <span>words</span></h1>
        </div>
    <div id="creation" class="border">
        <button type="button"
        onclick="ButtonPress()">
        Start</button>

        <p style="text-align:center" id="infoText"></p>
        <p style="text-align:center" id="demo"></p>
    </div>

    </main>
</body>

<script>
        function ButtonPress() {
            let runs = prompt("How many runs?", "20");
            if (runs == null || runs == "") {
                alert("You didn't gave me a number... :(")
            } else if(isNaN(runs)){
                alert("Your input isn't a number.. :(")
            } else {
                createColors(runs);
            }
        };


        function createColors(runs = 20) {
            const ColorArray = new Array(
                    "Red",
                    "Green",
                    "Blue",
                    "Yellow",
                    "Purple",
                    "Orange",
                    "Black",
            );

            function getRandom(Array) {
                if(!Array || Array.length <= 0 || !Array[0]) throw new Error("GETRANDOM: Error pls provide an array!")
                return Array[Math.floor(Math.random()*Array.length)];
            } 
       
            const now = new Date()
            let number = 1;
            const waitTexts = new Array(
                "Creating...",
                "Please wait until I created all Colors!"
            )

            if(waitTexts.includes(document.getElementById('infoText').innerHTML)) { 
                alert(waitTexts[1])
                return document.getElementById('infoText').innerHTML = waitTexts[1];
            } else if(document.getElementById('infoText').innerHTML.includes("Created")) {
                document.getElementById('demo').innerHTML = ` `;
                document.getElementById('infoText').innerHTML = waitTexts[0];
            } else document.getElementById('infoText').innerHTML = waitTexts[0];

            for(i = 0; i < runs; i++) {
                setTimeout(() => {
                    const rColor = getRandom(ColorArray);
                    const rStyle = getRandom(ColorArray);
                    number++;

                    
                    if(number === 1) document.getElementById('demo').innerHTML = `<p style="color:${rStyle}">` + rColor + "</p>";
                    else document.getElementById('demo').innerHTML = document.getElementById('demo').innerHTML + `<p style="color:${rStyle}">` + rColor + "</p>";


                    if(number === (runs - 1)) {
                        document.getElementById('infoText').innerHTML = `<p>Created ${runs} Random Colors after ${~~(new Date() - now) / 1000} seconds</p>`;
                    }
                }, i * 100) 
            }
        }
    </script>
</html>
