<?php echo $this->createTemplateTop(); ?>

<body <?php if ($this->isMainPage()) { ?>class="index" <?php } ?>>
    <main>
        <div id="headline">
            <h1><span id="generateTitle">Generate</span> <span id="someTitle">some</span> <span id="typeTitle">colors</span> + <span id="generateTitle">Generate</span> <span id="someTitle">some</span> <span id="typeTitle">words</span></h1>
        </div>
        <div id="creation" class="border">
            <button type="button" onclick="ButtonPress()">
                Click to Start</button>
            <button type="button" onclick="getLastStats()">
                Get Last Stats</button>
            <button type="button" onclick="Eval()">
                Eval Something</button>
            <p style="text-align:center" id="infoText"></p>
            <p style="text-align:center" id="demo"></p>
        </div>
    </main>
</body>

<script src="./func.js"></script>

</html>
